### ISSUE TITLE
Bug effect on "spigot server 1.7 "    "V1.4.0.009"

### ISSUE THREAD

**Issue by Gohu29** [Mithion/ArsMagica2#1553] opened 2016-08-11 17:22 UTC
Hello, i have a proble with the version 1.4.0.009
So I will explain to you.
I have a lobby on my server it's just a vanilla with spigot 1.7
And when I give some effect to a player he will be kicked from the server.

Screenshot from the screen I have when I'm be kick. http://puu.sh/qxJhF/7f13bafccb.png

Pastebin from my client console: http://pastebin.com/2YJBR0fD

This problem doesn't happen with the version 1.4.0.008

In hope you can fix this, thanks for reading.

**Comment by TheIcyOne** [comment] 2016-08-12 17:47
Is the player able to reconnect after being kicked?

**Comment by Gohu29** [comment] 2016-08-14 13:00
Nop, I'm kicking again. When another player have effect around me i'm kicking too.

**Comment by xSable** [comment] 2016-08-19 23:39
You may have some mismatched potion ids.

This same issue occurs when two mods share the same ids for potion effects. If you have NEI, I suggest going into single player, and doing a dump of ALL potion ids, then do the same on the multiplayer and compare the .csv files. If you see two spots where the ids don't match up, find the config for that mod and fix it.

If that's not the problem, I got nothing.

I've noticed this happens with Blood Arsenal and Ars Magica 2.

**Comment by Gohu29** [comment] 2016-08-24 16:27
This problem happen when I launch Ars Magica alone without other mods.

**Comment by xSable** [comment] 2016-08-25 20:03
Oh, then no clue.

**Comment by jjtParadox** [comment] 2016-08-31 21:29
This is a duplicate of an older issue, but Ars heavily modifies how the vanilla potions are communicated between server and client. This modification happens on both server and client, and usually nothing goes wrong because the two sides are speaking the same language, so to say. However, if a server starts talking to Ars in the "vanilla" language, this issue comes up.

Due to the nature of ASM modification, it's really hard to fix this issue, and it may not be fixed in the near future.

**Comment by jjtParadox** [comment] 2016-09-03 18:05
Did anyone happen to grab that console log? Link's now dead.

**Comment by Gohu29** [comment] 2016-09-05 17:34
`[19:25:25] [Netty Client IO #3/INFO] [LiteLoader]: Baking listener list for PostLoginListener with 0 listeners
[19:25:25] [Netty Client IO #3/INFO] [FML]: Aborting client handshake "VANILLA"
[19:25:25] [Netty Client IO #3/INFO] [FML]: [Netty Client IO #3] Client side vanilla connection established
[19:25:25] [Netty Client IO #3/INFO] [NEIAddons]: Connected to new server, resetting commands
[19:25:26] [Client thread/INFO] [LiteLoader]: Baking listener list for PreJoinGameListener with 0 listeners
[19:25:26] [Client thread/INFO] [Armourer's Workshop]: Adding world access to world net.minecraft.client.multiplayer.WorldClient@37f8af3a
[19:25:26] [Client thread/INFO] [EnderCore]: Transforming Class [net.minecraft.inventory.ContainerRepair], Method [func_82848_d]
[19:25:26] [Client thread/INFO] [EnderCore]: Transforming net.minecraft.inventory.ContainerRepair Finished.
[19:25:29] [Client thread/INFO] [LiteLoader]: Baking listener list for JoinGameListener with 1 listeners
[19:25:29] [Netty Client IO #3/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(1) exceeds writerIndex(9): UnpooledHeapByteBuf(ridx: 9, widx: 9, cap: 9)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:263) ~[ByteToMessageDecoder.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:131) ~[ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149) [ReadTimeoutHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) [AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(1) exceeds writerIndex(9): UnpooledHeapByteBuf(ridx: 9, widx: 9, cap: 9)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1160) ~[AbstractByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:562) ~[AbstractByteBuf.class:?]
	at net.minecraft.network.PacketBuffer.readByte(SourceFile:496) ~[et.class:?]
	at net.minecraft.network.play.server.S1DPacketEntityEffect.func_148837_a(SourceFile:37) ~[in.class:?]
	at net.minecraft.util.MessageDeserializer.decode(SourceFile:40) ~[ez.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232) ~[ByteToMessageDecoder.class:?]
	... 19 more
[19:25:29] [Netty Client IO #3/INFO] [THAUMCRAFT]: Restoring client configs.
[19:25:29] [Netty Client IO #3/INFO] [EnderCore]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[19:25:29] [Netty Client IO #3/INFO] [EnderCore]: Reset configs to client values for tterrag.wailaplugins.config.WPConfigHandler
[19:25:29] [Client thread/INFO] [LiteLoader]: Baking listener list for ChatListener with 0 listeners
[19:25:29] [Netty Client IO #3/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(1) exceeds writerIndex(9): UnpooledHeapByteBuf(ridx: 9, widx: 9, cap: 9)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:263) ~[ByteToMessageDecoder.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:131) ~[ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149) [ReadTimeoutHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) [AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(1) exceeds writerIndex(9): UnpooledHeapByteBuf(ridx: 9, widx: 9, cap: 9)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1160) ~[AbstractByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:562) ~[AbstractByteBuf.class:?]
	at net.minecraft.network.PacketBuffer.readByte(SourceFile:496) ~[et.class:?]
	at net.minecraft.network.play.server.S1DPacketEntityEffect.func_148837_a(SourceFile:37) ~[in.class:?]
	at net.minecraft.util.MessageDeserializer.decode(SourceFile:40) ~[ez.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232) ~[ByteToMessageDecoder.class:?]
	... 19 more`

**Comment by jjtParadox** [comment] 2016-09-06 22:28
Didn't need a revert, just a little clever coding :smiley:

**Closed** 2017-07-31 21:54 UTC
