### ISSUE TITLE
Previous spell keybind for spell books triggers next spell

### ISSUE THREAD

**Issue by DLemberg** [Mithion/ArsMagica2#1081] opened 2015-02-19 04:38 UTC
Using AM2 1.7.10 1.4.0.008, if you equip a spell book with multiple spells, both the previous spell (default z) and the next spell (default x) keys both trigger the next spell to be selected, instead of z selecting the prior spell as expected.  Happens in both single player and multiplayer.

**Comment by Mithion** [comment] 2015-02-19 19:33
This has already been fixed in dev.

Duplicate of #1065 and #1041 .

**Closed by Mithion** 2015-02-19 19:33 UTC
