### ISSUE TITLE
Gates are not accessible by any player in MP, except Host.

### ISSUE THREAD

**Issue by SangurianSoul** [Mithion/ArsMagica2#1104] opened 2015-03-01 00:12 UTC
When in MP, using LAN specifically, only the Host of the game can use gates.

Right clicking the portal will not activate the portal effect or create the sound effect. Nor with the aid of the keystone. Other players off and on can open the receptacles. The host can sometimes can not open the receptacle even with appropriate keystone. But the host can always activate the portal. And is the only one that can walk through.

Other players cant even use gates if they are the sole builder of the structure.

**Comment by Mithion** [comment] 2015-03-01 03:23
Can they access chests, etc. in the same area?
Does the gate have a rune combination set?

**Comment by ryukra** [comment] 2015-03-02 20:52
We have the same problem.. the solution to this was that all players have to wear the Magitech Goggles once.

**Comment by SangurianSoul** [comment] 2015-03-03 16:32
Yes they can access anything in the same area. Anything at all, just not the activation of the portal. They can occasionally open the interface to the Keystone Receptacle, but that is it. And we aren't sure how they do that when it happens.

It is the same problem with and without rune combinations. Once we figured out it was a problem, we stepped into a brand new world and tried tons of different combinations and the like. Different set ups, different combinations, different numbers of gates on the same combination.
While i am here, i do have a question, where Gates that have a rune combo only accessible by a Keystone with the same combo your original design? Or are Gates that share the same combination should be able to link to each other without a keystone?

Date: Sat, 28 Feb 2015 19:23:48 -0800

**Comment by sandalle** [comment] 2015-03-04 19:20
On a [Modderation: Permabanned](http://www.technicpack.net/modpack/modderation-permabanned-edition.449941) server I (opped), and all of my players (some opped, some not), are able to use Ars Magica 2 (1.4.0.008) Gateways. I currently have three Gateways, all rune locked, and each of my players has a Rune Bag with a Keystone and are able to use all three gateways to go to any of the other two. Not all of the players have worn the Magitech Goggles. This is a dedicated server running Linux, Forge Mod Loader 10.13.2.1291, and Java 1.8, if that differs from running an MP server in LAN mode from a client.

**Comment by Mithion** [comment] 2015-03-06 14:39
I have yet to be able to replicate this - I'm thinking it may either be lag or  an unsupported server framework - can you post a server log after this happens?

**Comment by SangurianSoul** [comment] 2015-03-07 02:39
Sure, where would i get this? minecraft doesnt crash or anything.
I also just use normal minecraft and use the LAN to play with family. Im not using anything extra.

Date: Fri, 6 Mar 2015 06:39:19 -0800

**Comment by Mithion** [comment] 2015-04-09 14:47
Sorry, I thought I had replied to this one - I'm looking for the FML-Server-0.log, or something similar.  They'll either be in a logs dir under the instance, or in the same folder as the server jar itself (depending on the forge version you are running).

**Comment by SangurianSoul** [comment] 2015-04-13 18:32
We have been using Mystcraft portals to get around at the moment, so im not sure which log will be helpful.
im sending you the latest log for each day around the time i had sent in the bug
Hopefully one of them has what you need

Date: Thu, 9 Apr 2015 07:47:11 -0700

**Comment by Mithion** [comment] 2015-06-25 00:22
The issue pertains to packets and how they work in LAN.
Power data isn't properly sync'd to the clients, as the packets seem to be redirected to the host at random.
This works just fine in SMP dedicated, so I am not sure what is doing this.

**Comment by jjtParadox** [comment] 2015-10-16 19:25
A friend of mine and I tried to replicate this bug with the dev version of AM2, but we weren't able to reproduce it. Has anyone else had luck replicating this bug?

**Comment by Mithion** [comment] 2015-10-26 17:28
I still can't reproduce it.  I'm going to close this as unable to reproduce, and if the issue persists in 1.4.0.009, we can re-open the issue and investigate further.

**Closed by Mithion** 2015-10-26 17:28 UTC
Labels: bug

**Comment by SangurianSoul** [comment] 2015-10-28 16:09
Okay. i will let you know if it persists in the next version.

Date: Mon, 26 Oct 2015 10:28:39 -0700
