### ISSUE TITLE
Buffs and potion effects are all mixed up and wrong (version .008)

### ISSUE THREAD

**Issue by Darkmega18** [Mithion/ArsMagica2#1074] opened 2015-02-14 17:49 UTC
Whenever I use spells that are meant to give me buffs, most notably a spell with haste, swift swim and leap on it instead of getting the potion effects for those spells I get standard block breaking haste, blindness and hunger and my screen begins to spaz out rapidly as if it knows I should have the spell effects but something else is interfering and competing with it. I thought it was the potion IDs but they were fine. I thought it was forbidden magic's AM2 support being unrecommended but turning that off, it's still the same.

I'm still fiddling with my pack to find out what is wrong but for now I figured I'd post a report and send in the forge log here for you to look at if you know or have seen the problem.  https://dl.dropboxusercontent.com/u/39619820/latest.log

Also, the mana potions are giving me regeneration instead of mana regeneration and the large buff bar at the top of my screen seems to know what the effects are "meant to be" but the small buff bar from ars around my cursor doesn't and displays the ones it thinks they are. The other spells that don't involve potion effects are working as intended. Other than dig completely evaporating strongboxes and other such things but that's already been reported.

.... and is there a reason you extended the potion IDs just for your stuff and if I try to set them down to the normal values it throws a negative value outofbounds crash?

**Comment by YWZMatt** [comment] 2015-02-14 21:26
I'm having the exact same problems as you. Really annoying.

**Comment by Darkmega18** [comment] 2015-02-15 03:14
I see I see... well I'm not outing thaumcraft or ars themselves because they'll mess up everything in my quest book and I'd rather avoid that if I could... however...
[CUE PROFESSOR LAYTONS THEME!] https://www.youtube.com/watch?v=ZVJDGes4Fj4

despite not being a coder I think the potion effects (due to unforseen interactions from other mods) are causing the extended potion IDs to loop around... 
because I have a potion ID dump from NEI that tells me all the potion IDs and so I see that potion ID 3 is actually dig speed, standard issue haste buff. if you look at the extended ars IDs and go to haste that ID is actually the 4th potion ID down the list (counting the first as zero, as is how programming goes). 
While the ID 16 is actually blindness. one of the things I have in my spell is swift swim, that is actually the 17th potion ID in the ars magica extended IDs. 
and ditto with hunger being 2 slots after that in position ID 18. Leap is actually 2 potion IDs directly under that aswell.
Now, i also get regeneration when I chug a mana potion. So if we got to regeneration thats ID 10... 11th slot of ars magica, or 10th if you call the first one zero like you should, that coincides with mana regeneration which you're meant to get off mana potions as a secondary effect.
Although in some cases the potion effect works, such as mana boost from an etherium potion, but it still also gives me weakness from down the list but I do seem to still get my mana boost.
There seems to be a super deadly overlap/loop-around going on that causes the game to think the ID are something else, and so in game they apply those effects and they do, but also because my screen starts glitching out and my big buff bar from... I think it's zelda sword skills, is showing the right icons I believe the game also thinks that the buffs that are meant to be applied are being applied, and so explaining my spazzing out view point as the view but because it's not actually there ars and the game start arguing with each other causing shenanigans... :V

So... howabout that?

**Comment by YWZMatt** [comment] 2015-02-15 03:52
Well until there is an official response, I would recommend looking at your potion.csv to see if there are any mods that add a decent number of potions that you don't care much about. Personally I removed brewcraft from my modpack and now despite displaying things like wither or "sticky items" the actual effects from spells are correct.

**Comment by Darkmega18** [comment] 2015-02-15 07:45
Trust me when I say, "If I didn't care about a mod, I wouldn't have it in the first place". So yeah, I've just basically said to myself, "if it gives an ars magica 2 buff, don't use it". Besides, I've got 20 other starting gear equipment quests worth of stuff to select from and attempt to use in my modpack's world to play around with while I wait.... and quite frankly with all the stuff I end up doing, I tend to not get too far into ars without getting distracted into another thing. Only reason I came across this was cause I start the ars magica specializing players off with a spell called "Spirit of travel" which combines basic haste, swiftswim and leap as a spell among others like a basic dig, basic arcane damage and basic multi-targetable heal spell. So when I was testing to make sure the equipment was coming out of the quest book properly I just ran into it randomly when using the spells periodically for early game levels. :V

**Comment by Bahzur** [comment] 2015-02-15 09:02
Got the same here, but happens only to waterbreathing for me and replaces it with Taint Withdrawl. Still got the effect from waterbreathing though.

**Comment by YWZMatt** [comment] 2015-02-15 12:09
Perhaps you could try something similar to what I did? If your (non Ars Magica) mods support changing the potion IDs, you could try changing them, then deleting the AM2 config and having it automatically fill itself into the gaps. After deleting brewcraft, a few spell effects still didn't work, so I ended up doing something very similar to what I have just detailed.

**Comment by Bahzur** [comment] 2015-02-15 12:16
The only conflict i got is with Thaumcraft, and i couldnt find any reference to potion ids in its config, only in AM2's config i found potion ids. The next thing i wanted to try next time i restart the server is moving the waterbreath potion id around (the only one that seems to conflict with Thaumcraft) in the config of AM2. I dont think i have more than these two mods that add potions/effects.

**Comment by Mithion** [comment] 2015-02-15 18:23
This is why I didn't want to make potion ids configurable.
The reason that ars seems to know what buffs are what is that it keeps track internally of the id mappings. 
What's happening here is that they are configured as the same id as another potion. Since it obeys the config blindly (as it should), it overwrites the other potion effect there. I believe I added in a warning in configs to tell you that there's a conflict, but I'm not certain. 

You need to configure the ids to something unused. The NEI potion id dump can help with that. You can also try deleting that entire section of the config and letting it regenerate, but you may get mixed results based on mod load order.

**Comment by Darkmega18** [comment] 2015-02-15 22:04
well... after nudging all other mod's Potion IDs up the list and then slotting ars stuff at the front it seems to have stopped giving me a negative out of bounds crash now. so... ... meh. whatever.... 
and it probably need a new thread, but swift swim isn't doing anything in my pack. 
Know of any mods that would affect that? 
and isn't the haste spell meant to give step assist while it's on or am I thinking of a different spell?

**Comment by Mithion** [comment] 2015-02-16 13:42
Haste won't give step assist, no.
There is an armor imbuement that will though (leg slot).

I noticed that swift swim wasn't working in my own test world too, so I've already replicated that one.  Actually, I think it does work, but it isn't applying enough of a boost...I should try to add buff power and see if it makes a difference.

**Comment by Mithion** [comment] 2015-02-16 13:45
I'm closing this as "not a bug", as this is due to the potion IDs being configurable...it removes all logic and AM2 won't attempt to fix things for you anymore - it must be fixed manually in the config file.  That being said, I'll see if I can make it a tiny bit smarter to assist with configuring, but honestly, this is pretty much the intended behaviour.  It'll do whatever you configure it to do.

**Closed by Mithion** 2015-02-16 13:45 UTC

**Comment by Bahzur** [comment] 2015-02-16 15:38
Fair enough. Thx Mithion!

**Comment by Darkmega18** [comment] 2015-02-18 06:32
roger roger. reconfiguring was the first thing I tried actually, but like I said, all the big mods already had their IDs in the front of the list and when I applied yours to the upper reaches of the 150+ area they blew up and said something about out of bounds with a negative value which is what made me come to here before trying to outright move all the IDs up and then put yours at the start where in the end they didn't blow up anymore. So yeah, I'll be remembering to try that next time potion IDs blow up in the upper half of the potion IDs. >_<

**Comment by sandalle** [comment] 2015-03-02 18:48
I'm having this issue on my server (running [Modderation: Permabanned](http://www.technicpack.net/modpack/modderation-permabanned-edition.449941)) and my AM2/AM2.cfg has no hard-coded potion configs. e.g. Leap (Jump; Potion ID 8) gives me Poison (ID 19) effect, but that Status bar on the right says Hunger (ID 17). My ability to jump is not improved at all. ;) This might be why #1048 causes disconnects.

I have even wiped both my server and client configs and let them regenerate and still have this issue, and still AM2/AM2.cfg does not list any hardcoded potion IDs, so I'm at a loss as to where I go to fix this issue. 

My potions.csv (dumped via NEI) and has no Potion ID conflicts in dumps/potions.csv. No other mods (Tested: vanilla Night Vision potion, Xeno's Reliquary Elixir of Bounding (Jump Boost II), Botania Flask of Upsurging (Jump Boost II), Ender IO gear with effects (e.g. Dark Boots with Jump III; doesn't appear to apply a potion effect), Magical Crops Night Vision Potion, Project E gear (Gem Helmet with Night Vision; applies the potion effect when in areas of darkness)) appear to be having issues with potions (neither in their effect applied to me nor with the Status display).

If there are other spells/combinations/configs you'd like me to test, let me know as I have full access to this server and backups of the world. :)

**Comment by sandalle** [comment] 2015-03-03 07:04
Ahh, I found it. The *client* generates the full AM2/AM2.cfg which will include the potion IDs to use. I was depending on the *server* to generate the configuration files and then I pushed that file to the clients. Loading a world with the client (with clean configs) and then copying the AM2/AM2.cfg to the server (so both client and server match) seems to fix the potion ID mismatch. Leap now gives me Leap, instead of Poison (with a confused Status of Hunger). ;)

**Comment by Mithion** [comment] 2015-03-03 11:13
Nice - I'm glad you were able to fix it :)
Configuration can be a pain at times.

**Comment by kotoroshinoto** [comment] 2015-04-24 08:03
the configs dont seem to have potion values in them

**Comment by kotoroshinoto** [comment] 2015-04-24 09:10
I changed the IDS: 

potions {
    I:agility=33
    I:astraldistortion=34
    I:burnoutredux=35
    I:charmed=36
    I:chronoanchor=37
    I:clarity=38
    I:entangled=39
    I:featherfall=40
    I:flight=41
    I:frostslow=42
    I:fury=43
    I:gravitywell=44
    I:haste=45
    I:illuminated=46
    I:leap=47
    I:levitation=48
    I:magicshield=49
    I:manaboost=53
    I:manaregen=54
    I:manashield=55
    I:regeneration=56
    I:scramblesynapses=57
    I:shrunken=58
    I:silence=59
    I:spellreflect=60
    I:swiftswim=61
    I:truesight=62
    I:waterbreathing=63
    I:waterygrave=64
}

however NEI outputs these: 

33,Agility,am2.buffs.ArsMagicaPotion
34,Astral Distortion,am2.buffs.ArsMagicaPotion
35,Burnout Redux,am2.buffs.ArsMagicaPotion
36,Charmed,am2.buffs.ArsMagicaPotion
37,Chrono Anchor,am2.buffs.ArsMagicaPotion
38,Clarity,am2.buffs.ArsMagicaPotion
39,Entangled,am2.buffs.ArsMagicaPotion
40,Feather Fall,am2.buffs.ArsMagicaPotion
41,Flight,am2.buffs.ArsMagicaPotion
42,Frost Slow,am2.buffs.ArsMagicaPotion
43,Fury,am2.buffs.ArsMagicaPotion
44,Gravity Well,am2.buffs.ArsMagicaPotion
45,Haste,am2.buffs.ArsMagicaPotion
46,Illuminated,am2.buffs.ArsMagicaPotion
47,Leap,am2.buffs.ArsMagicaPotion
48,Levitation,am2.buffs.ArsMagicaPotion
49,Magic Shield,am2.buffs.ArsMagicaPotion
53,Mana Boost,am2.buffs.ArsMagicaPotion
54,Mana Regen,am2.buffs.ArsMagicaPotion
55,Mana Shield,am2.buffs.ArsMagicaPotion
56,Greater Mana Restoration,am2.buffs.ManaPotion
57,Epic Mana Restoration,am2.buffs.ManaPotion
58,Shrunken,am2.buffs.ArsMagicaPotion
59,Silence,am2.buffs.ArsMagicaPotion
60,Spell Reflect,am2.buffs.ArsMagicaPotion
61,Swift Swim,am2.buffs.ArsMagicaPotion
62,True Sight,am2.buffs.ArsMagicaPotion
63,Water Breathing,am2.buffs.ArsMagicaPotion
64,Watery Grave,am2.buffs.ArsMagicaPotion


these clearly do not match... what the heck is going on?
