### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by HunterHero1234** [Mithion/ArsMagica2#1441] opened 2016-02-24 15:50 UTC
http://pastebin.com/htgHTS1d

Edited to use pastebin
--Mithion.

**Comment by jjtParadox** [comment] 2016-02-25 21:45
First, update to version AM2 v *.009, then let us know if this still happens

(Duplicate of #1190)

**Comment by Mithion** [comment] 2016-02-25 21:47
Also, make sure to use pastebin with future crash logs (if any).  Helps to keep things nice and clean.
The more you can tell us about how to reproduce the error as well, the better.

**Comment by HunterHero** [comment] 2016-02-26 19:31
wheres the 1.7.2 version

**Comment by jjtParadox** [comment] 2016-02-27 15:15
1.7.2 is old and no longer supported, as 1.7.10 is the current supported version. It can be found on CurseForge.

**Comment by TheIcyOne** [comment] 2016-02-29 00:01
You're using 1.7.10 anyway, @HunterHero . The 1.7.2 version of AM2 would be incompatible.

**Comment by HunterHero** [comment] 2016-03-04 14:42
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 3/4/16 9:35 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at am2.guis.GuiSkillTrees.func_73866_w_(GuiSkillTrees.java:102)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
	at am2.proxy.ClientProxy.openSkillTreeUI(ClientProxy.java:188)
	at am2.blocks.BlockOcculus.func_149727_a(BlockOcculus.java:59)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at am2.guis.GuiSkillTrees.func_73866_w_(GuiSkillTrees.java:102)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
	at am2.proxy.ClientProxy.openSkillTreeUI(ClientProxy.java:188)
	at am2.blocks.BlockOcculus.func_149727_a(BlockOcculus.java:59)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['LegendHunterHero'/58, l='MpServer', x=-612.65, y=7.62, z=389.87]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-677,4,396), Chunk: (at 11,0,12 in -43,24; contains blocks -688,0,384 to -673,255,399), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 31648 game time, 31648 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 25 total; [EntityPig['Pig'/30, l='MpServer', x=-680.91, y=6.00, z=357.84], EntityChicken['Chicken'/31, l='MpServer', x=-673.06, y=6.00, z=454.03], EntityPig['Pig'/32, l='MpServer', x=-658.91, y=6.00, z=326.97], EntityPig['Pig'/33, l='MpServer', x=-657.28, y=6.00, z=359.13], EntityItemFrame['entity.ItemFrame.name'/342631, l='MpServer', x=-614.94, y=7.50, z=393.50], EntityPig['Pig'/35, l='MpServer', x=-657.19, y=6.00, z=469.16], EntityPig['Pig'/36, l='MpServer', x=-662.13, y=6.00, z=471.28], EntityPig['Pig'/38, l='MpServer', x=-654.28, y=6.00, z=336.91], EntityPig['Pig'/39, l='MpServer', x=-644.97, y=6.00, z=337.13], EntityPig['Pig'/40, l='MpServer', x=-649.03, y=6.00, z=336.13], EntityPig['Pig'/41, l='MpServer', x=-650.84, y=6.00, z=367.59], EntityPig['Pig'/42, l='MpServer', x=-639.19, y=6.00, z=363.28], EntitySheep['Sheep'/43, l='MpServer', x=-636.88, y=6.00, z=430.91], EntitySheep['Sheep'/45, l='MpServer', x=-637.94, y=6.00, z=372.03], EntityCow['Cow'/46, l='MpServer', x=-584.72, y=6.00, z=326.31], EntitySheep['Sheep'/47, l='MpServer', x=-579.88, y=6.00, z=320.78], EntitySheep['Sheep'/48, l='MpServer', x=-573.19, y=6.00, z=382.63], EntitySheep['Sheep'/49, l='MpServer', x=-584.41, y=6.00, z=392.59], EntityCow['Cow'/51, l='MpServer', x=-563.03, y=6.00, z=332.91], EntityCow['Cow'/52, l='MpServer', x=-550.22, y=6.00, z=344.22], EntityChicken['Chicken'/53, l='MpServer', x=-548.72, y=6.00, z=443.34], EntityChicken['Chicken'/54, l='MpServer', x=-545.53, y=6.00, z=439.53], EntityChicken['Chicken'/55, l='MpServer', x=-550.50, y=6.00, z=439.50], EntityChicken['Chicken'/56, l='MpServer', x=-553.47, y=6.00, z=453.53], EntityClientPlayerMP['LegendHunterHero'/58, l='MpServer', x=-612.65, y=7.62, z=389.87]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 117938920 bytes (112 MB) / 376098816 bytes (358 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1481} [Minecraft Forge] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) 
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2302' Renderer: 'Intel(R) G41 Express Chipset'
	Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) G41 Express Chipset GL version 2.1.0 - Build 8.15.10.2302, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because EXT_framebuffer_object is supported.
Anisotropic filtering is supported and maximum anisotropy is 2.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by HunterHero** [comment] 2016-03-04 14:43
crashes when i open the occulus

**Comment by Mithion** [comment] 2016-03-04 15:17
And I say again:

PASTE.  BIN.  PLEASE.

**Comment by Mithion** [comment] 2016-03-04 15:18
If you need the address, all you do is go to:
http://pastebin.com/

and paste the issue there.  Give it a title, and click "Create new Paste".
Keeps things much cleaner.

**Comment by HunterHero** [comment] 2016-03-04 15:32
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 3/4/16 9:35 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at am2.guis.GuiSkillTrees.func_73866_w_(GuiSkillTrees.java:102)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
	at am2.proxy.ClientProxy.openSkillTreeUI(ClientProxy.java:188)
	at am2.blocks.BlockOcculus.func_149727_a(BlockOcculus.java:59)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at am2.guis.GuiSkillTrees.func_73866_w_(GuiSkillTrees.java:102)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
	at am2.proxy.ClientProxy.openSkillTreeUI(ClientProxy.java:188)
	at am2.blocks.BlockOcculus.func_149727_a(BlockOcculus.java:59)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['LegendHunterHero'/58, l='MpServer', x=-612.65, y=7.62, z=389.87]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-677,4,396), Chunk: (at 11,0,12 in -43,24; contains blocks -688,0,384 to -673,255,399), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 31648 game time, 31648 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 25 total; [EntityPig['Pig'/30, l='MpServer', x=-680.91, y=6.00, z=357.84], EntityChicken['Chicken'/31, l='MpServer', x=-673.06, y=6.00, z=454.03], EntityPig['Pig'/32, l='MpServer', x=-658.91, y=6.00, z=326.97], EntityPig['Pig'/33, l='MpServer', x=-657.28, y=6.00, z=359.13], EntityItemFrame['entity.ItemFrame.name'/342631, l='MpServer', x=-614.94, y=7.50, z=393.50], EntityPig['Pig'/35, l='MpServer', x=-657.19, y=6.00, z=469.16], EntityPig['Pig'/36, l='MpServer', x=-662.13, y=6.00, z=471.28], EntityPig['Pig'/38, l='MpServer', x=-654.28, y=6.00, z=336.91], EntityPig['Pig'/39, l='MpServer', x=-644.97, y=6.00, z=337.13], EntityPig['Pig'/40, l='MpServer', x=-649.03, y=6.00, z=336.13], EntityPig['Pig'/41, l='MpServer', x=-650.84, y=6.00, z=367.59], EntityPig['Pig'/42, l='MpServer', x=-639.19, y=6.00, z=363.28], EntitySheep['Sheep'/43, l='MpServer', x=-636.88, y=6.00, z=430.91], EntitySheep['Sheep'/45, l='MpServer', x=-637.94, y=6.00, z=372.03], EntityCow['Cow'/46, l='MpServer', x=-584.72, y=6.00, z=326.31], EntitySheep['Sheep'/47, l='MpServer', x=-579.88, y=6.00, z=320.78], EntitySheep['Sheep'/48, l='MpServer', x=-573.19, y=6.00, z=382.63], EntitySheep['Sheep'/49, l='MpServer', x=-584.41, y=6.00, z=392.59], EntityCow['Cow'/51, l='MpServer', x=-563.03, y=6.00, z=332.91], EntityCow['Cow'/52, l='MpServer', x=-550.22, y=6.00, z=344.22], EntityChicken['Chicken'/53, l='MpServer', x=-548.72, y=6.00, z=443.34], EntityChicken['Chicken'/54, l='MpServer', x=-545.53, y=6.00, z=439.53], EntityChicken['Chicken'/55, l='MpServer', x=-550.50, y=6.00, z=439.50], EntityChicken['Chicken'/56, l='MpServer', x=-553.47, y=6.00, z=453.53], EntityClientPlayerMP['LegendHunterHero'/58, l='MpServer', x=-612.65, y=7.62, z=389.87]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 117938920 bytes (112 MB) / 376098816 bytes (358 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1481} [Minecraft Forge] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) 
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2302' Renderer: 'Intel(R) G41 Express Chipset'
	Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) G41 Express Chipset GL version 2.1.0 - Build 8.15.10.2302, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because EXT_framebuffer_object is supported.
Anisotropic filtering is supported and maximum anisotropy is 2.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Mithion** [comment] 2016-03-04 15:33
Closed, locked, and done.

**Closed by Mithion** 2016-03-04 15:33 UTC
