### ISSUE TITLE
Major Ore Smelting Bug

### ISSUE THREAD

**Issue by Zsashas** [Mithion/ArsMagica2#1324] opened 2015-10-10 02:12 UTC
It seems that the following can all be smelted into a single Vinteum Dust in any furnace:

Vinteum Ore
Vinteum Block
Chimerite Ore
Chimerite Block
Sunstone Ore
Sunstone Block
Moonstone Ore
Moonstone Block
Blue Topaz Ore
Blue Topaz Block

**Comment by LemADEC** [comment] 2015-11-10 21:15
what version are you using?
are there any other mods involved?
is it in single or multiplayer only?

**Comment by Zsashas** [comment] 2015-11-10 22:26
Single player, latest version.

Mod list is about 150 mods, but I don't have any that should be messing with this. No other mods are affected.

**Comment by LemADEC** [comment] 2015-11-11 02:29
Your the only one with that issue so far, so there's most probably a interaction between mods.
Backup your world, remove half of your mods and see if still reproduce the issue, and so on, until you have the strict minimum required to reproduce the issue.
Share you mods list and version, we might be able to propose some mods to start removing first.

**Comment by Zsashas** [comment] 2015-11-11 22:35
This seems to be something deeper. It only applies to vanilla furnace recipes in NEI, and I just found that NEI also shows Hydraulicraft Lead Ore smelting into Railcraft Steel Ingots (again, only in a vanilla furnace).

**Comment by LemADEC** [comment] 2015-11-11 23:35
looks like ID overlapping more than anything else

**Comment by Zsashas** [comment] 2015-11-12 07:05
But that many items from the same mod?

**Comment by Zsashas** [comment] 2015-11-12 07:06
Do you happen to know the format for MineTweaker furnace scripts so I can fix this?

**Comment by LemADEC** [comment] 2015-11-12 10:20
You need to try removing mods, there's probably one forcing its IDs instead of using FML to allocate them, hence overlapping a whole range of them.
Either that or you have an existing script changing recipes using IDs instead of full name. Was this pack ported from 1.6.4 or older?

**Comment by Zsashas** [comment] 2015-11-12 20:02
No, the pack was made for 1.7.10. All scripts use names.

**Comment by LemADEC** [comment] 2015-11-12 20:47
Then it's time to start removing mods to narrow down the issue :)

**Comment by Zsashas** [comment] 2015-11-12 23:20
Some further testing with NEI, checking both Usage and Recipes:

Checking usage for Mooonstone ore in the furnace: https://gyazo.com/5b53e86ead87693edd886657c58c2f72

Checking recipes for Vinteum Dust in the furnace: https://gyazo.com/919678b14ebefa140f6d30b96169ba3f

Checking usage for Moonstone ore in Hydraulicraft's Friction Incinerator: https://gyazo.com/cfff978a4018f2f43f44848944c36983

That third one is odd, because it's showing the input item changing while the result stays the same, which is what would happen if checking recipes, not usage.

Sometimes NEI shows thing that aren't accurate, but the blocks do all smelt into vinteum dust. Fortunately, crushing and similar ore processing seems unaffected, only furnace recipes and other types that take it from the vanilla furnace (Ender IO Alloy Smelter seems unaffected)

Going to try testing with various mod combinations to see if I can find which one is responsible.

**Comment by LemADEC** [comment] 2015-11-12 23:34
did you try with your scripts disabled?
it looks like item metadata is being skipped/ignored somewhere.

**Comment by Zsashas** [comment] 2015-11-12 23:39
None of my scripts have anything to do with smelting, as I haven't tried that yet. Also, I jsut tested it with only the following mods:

DragonAPI (for potion IDs)
NEI
CCC
Ars Magica
Animation API

And it's still happening. Everything returns to vinteum. This is even without MineTweaker and ModTweaker, so no scripts.

**Comment by LemADEC** [comment] 2015-11-13 03:04
which version of those are you using?

**Comment by Zsashas** [comment] 2015-11-13 04:31
Latest version available for 1.7.10 of each mod.

**Comment by LemADEC** [comment] 2015-11-13 09:17
we need exact numbers

**Comment by Zsashas** [comment] 2015-11-13 09:47
AnimationAPI-1.7.10-1.2.4
CodeChickenCore-1.7.10-1.0.7.46-universal
DragonAPI 1.7.10 V9b
NotEnoughItems-1.7.10-1.0.5.111-universal
Z - 1.7.10_AM2-1.4.0.008


AM2 is renamed to be loaded after a mod that was causing a crash, but I can't remember which.

**Comment by LemADEC** [comment] 2015-11-13 20:08
When smeling ArsMagica ores into a vanilla recipes, the output is either Vinteum dust or the expected item, while it should never be Vinteum dust.
Issue is reproduced in SSP with
1.7.10-Forge10.13.2.1236
mods/am2-1.4.0.008
mods/AnimationAPI-1.7.10-1.2.4
(no others mods)

and

1.7.10-Forge10.13.4.1492-1.7.10
mods/am2-1.4.0.008
mods/AnimationAPI-1.7.10-1.2.4
(no others mods)

@Mithion this looks like a bug to fix before next release :)

**Comment by Zsashas** [comment] 2015-11-13 21:34
Also includes blocks of the ores.

**Comment by Zsashas** [comment] 2015-11-13 21:35
Which shouldn't even be smeltable in the first place.

**Comment by Zsashas** [comment] 2015-11-15 02:19
Looks like the blocks are all OreDicted as Vinteum Ore, that's why it's happening. I don't know why I didn't check that sooner.

**Comment by Zsashas** [comment] 2015-11-15 04:49
Ok, so I made a temporary script to fix this until the update, requires MineTweaker of course.

furnace.remove(<arsmagica2:itemOre:0>,<*>); // Removes all furnace recipes that result in a vinteum dust.
furnace.addRecipe(<arsmagica2:itemOre:0>,<arsmagica2:vinteumOre>);

**Comment by LemADEC** [comment] 2015-11-29 00:36
This bug is actually already fixed in the dev version
@Mithion you may close this one

**Closed** 2015-11-29 02:07 UTC
