### ISSUE TITLE
Dig spell often completely destroys blocks without any drops

### ISSUE THREAD

**Issue by twothe** [Mithion/ArsMagica2#1055] opened 2015-02-09 12:50 UTC
I learned that the dig spell often just destroys a block instead of "harvesting" them as it should. I have not seen any pattern with this.

Example: ExtraUtilites Drums

Since those are perfectly "minable" with a pickaxe there shouldn't be a reason (from the player's perspective) why the dig spell would destroy them.

**Comment by Bahzur** [comment] 2015-02-20 08:40
Yup, accidentally destroyed a tank from Ender IO with a digspell that has silktouch added.

**Comment by Bluexin** [comment] 2015-03-17 16:50
As a temporary fix I figured you can simply change this in the config AM2.cfg):
# Can the dig component break blocks that have a tile entity?
B:DigBreaksTileEntities=true
to false

(As I haven't had any problem anymore with this I guess it has something to do with TEs...)

**Comment by Mithion** [comment] 2015-06-02 13:32
Dig has been made smarter in 1.4.0.009 (dev).  This still requires testing to ensure the issue is fixed.

**Comment by Bahzur** [comment] 2015-06-02 22:11
Will tell if i find something!

**Comment by Mithion** [comment] 2015-06-04 02:44
All testing has indicated that this issue isn't happening with the updated Dig spell.
Closing as resolved for now, once 1.4.0.009 releases please re-test in your specific instance and update this thread if it's still happening.

**Closed by Mithion** 2015-06-04 02:44 UTC
Labels: bug
