### ISSUE TITLE
Buckets in the Magician's Workbench

### ISSUE THREAD

**Issue by dreadwraith** [Mithion/ArsMagica2#1295] opened 2015-09-26 00:32 UTC
I noticed that when making cake in the magician's workbench (haven't been able to test with other recipes) that where a crafting table would return 3 empty buckets, the workbench returns the buckets and keeps 3 milk buckets in the crafting grid, resulting in an ever growing amount of buckets.

**Comment by dreadwraith** [comment] 2015-09-26 00:46
Through further testing, I can confirm that this occurs in both single player and on servers, and does not appear to be occurring with other recipes that return byproducts, such as the blood magic sigil crafting (returns the blood orb as a byproduct).

**Comment by EoD** [comment] 2015-09-26 11:38
I was not able to reproduce this in 6c490c22dfabd4204def90b11e0db2f3da45edb2 . 

Just to be sure, I put the recipe in the left area and then I used the left mouse button to withdraw the cake from the lower bit:
![2015-09-26_13 35 50](https://cloud.githubusercontent.com/assets/293499/10117336/a26b96ee-6453-11e5-9d9a-394a3b969844.png)

The empty buckets stayed in the crafting grid, no buckets dropped into my inventory (I also tried it with an empty inventory).

**Comment by EoD** [comment] 2015-09-26 11:42
Ah, this is a duplicate of #1029.

**Comment by Mithion** [comment] 2015-09-26 13:55
Closing as duplicate.

**Closed by Mithion** 2015-09-26 13:55 UTC
Labels: duplicate
