### ISSUE TITLE
Crash when using Divine Intervention (unplayable)

### ISSUE THREAD

**Issue by kiomadoushi** [Mithion/ArsMagica2#973] opened 2014-12-07 12:02 UTC
Just a simple [Self - Divine Intervention] spell. Crashed when using it once in the nether, and crashed again when the world finally loaded to try to return to my bed. Minecraft now completely closes instantly when the world loads, making the save unplayable. Luckily it was just my creative singleplayer world - I like to test mana costs and ease of use with my spells away from my main world - but unplayable is still a problem. I fear ever using it now or permanently destroying our multiplayer world.

Natural Magic modpack
http://www.atlauncher.com/pack/NaturalMagic

AM2 v1.4.0.005

Crash going from Nether to Overworld:
http://pastebin.com/mAirgVDH

Crash going from Overworld to Home (Overworld):
http://pastebin.com/9gQBHqHU

Crash on subsequent world load:  (don't know if it's any different, but it's a separate crash report)
http://pastebin.com/UTuWyUCU

I have more world-load crash reports, from each time to see if it was just like a one-time thing (or five-time...)

**Comment by Mithion** [comment] 2015-01-19 22:38
All the pastes expired (or were removed) before I could get to them.  Do you still have the log files?

**Comment by Mithion** [comment] 2015-01-20 19:01
Duplicate of #798

**Closed by Mithion** 2015-01-20 19:01 UTC
Labels: Waiting on Information
