### ISSUE TITLE
Invisible block

### ISSUE THREAD

**Issue by Amphilohiy** [Mithion/ArsMagica2#969] opened 2014-12-01 17:34 UTC
I'm tried ti make some AM tower, so nothing from other mods (except aesthetic) wasn't in this tower. On first floor i placed obelisk and load some vinteum dust in it. Then, i moved it outside near the altar to make spell that requires etherium. After some wrench madness (shift right clicking the altar and trying to disable link mode) i complete the spell and tried to place obelisk back, but some invisible block takes it's place.
Tried to spill some daylight (in case of invisible hecate). Tried to fit any microblock in there, but i could only cover it outside 1x1x1 block. Placed some sand on it, and sand is floating. If sand falls on this, it's behave like a torch, and sand drops as item.
![am2issue](https://cloud.githubusercontent.com/assets/10032171/5249986/92c098ae-79ba-11e4-86f9-911a26a8246b.jpg)

P.S. Well, i placed obelisk back, i just put water in this block (and appeared red particles), and then i was able to replace water. But it's not solved whole problem, i put sand on this water, then shovel it, and invisible block reappears.
Link to gif http://i.imgur.com/Vjd0WC3.gif

P.P.S. The problem appears as you link obelisk to etherium conduit. I just broke conduit and do all the stuff with water, and invisible block disappeared.

**Comment by EoD** [comment] 2015-01-05 09:30
Sounds very much like a duplicate of #932

**Comment by Mithion** [comment] 2015-01-19 22:38
This has been corrected in 1.4.0.007 (dev).

**Closed by Mithion** 2015-01-19 22:38 UTC
