### ISSUE TITLE
Spellbook prev and next keys not working.

### ISSUE THREAD

**Issue by YWZMatt** [Mithion/ArsMagica2#1110] opened 2015-03-03 14:38 UTC
Both keys result in the equivalent of sneak+scrolldown, as if they were both the same key. Quite annoying as I would like to assign those keys, then assign my extra mouse buttons to them for easy spell switching without accidentally opening the spellbook when casting quickly after scrolling.

Tested in MP and SP with both Arcane and normal spell book.

**Comment by Bahzur** [comment] 2015-03-03 15:20
Duplicate of #1041

**Closed** 2015-03-03 15:21 UTC
Labels: duplicate
