### ISSUE TITLE
Everything reset on death/relaunch

### ISSUE THREAD

**Issue by ThatOneTraitor** [Mithion/ArsMagica2#1367] opened 2016-01-05 10:25 UTC
anytime i relaunch or die, everything gets reset, affinities, levels, taught spells, infinity orbs used, everything, i'm running the modpack "devour the world," Thanks for reading :smile: Edit: Running the most recent version of AM2 on curse (1.4.0.008)

**Comment by jjtParadox** [comment] 2016-01-25 21:45
I believe this has been fixed in dev and can be closed. If the issue persists after the next update, feel free to re-open this or post a new issue.

**Closed** 2016-01-25 21:58 UTC

**Comment by rob5251** [comment] 2016-02-14 21:56
This issue is occurring for multiple people on my SMP server, we are using version 1.4.0.009

**Comment by bookerthegeek** [comment] 2016-02-14 22:56
1.4.0.009 is not the dev.

**Comment by rob5251** [comment] 2016-02-15 00:10
@bookerthegeek Ah, I figured 009 was suppose to be the fixed version, sorry about that. :+1:

**Comment by jjtParadox** [comment] 2016-02-15 13:54
By "in dev" I _did_ mean the up and coming 009 update. It was an issue in 008 that we thought we fixed. @rob5251, can you spare a few more details as to what's going on?

**Comment by rob5251** [comment] 2016-02-15 18:05
I thought it may be caused by player death, but more than likely this is occurring after the server restarts as far as I can tell. I've had no issue with any other data being lost other than ars magica. I know that the server is definitely running a "save-all" on every restart.

**Comment by jjtParadox** [comment] 2016-02-16 18:54
Do the players have altered usernames on that server? Username changes have caused problems in the past, but that should have been fixed with version 009. A server in offline mode may also cause issues.

**Comment by rob5251** [comment] 2016-02-16 19:00
Server is not in offline mode, no one has changed their username.

**Comment by jjtParadox** [comment] 2016-02-16 19:24
Hmm... does it always happen on death, or only in certain conditions (e.g. in a certain dimension, killed by a certain thing, etc.)?

**Comment by rob5251** [comment] 2016-02-16 20:08
It's kind of random to be honest.
Usually all is fine, I get on the next day and someone tells me all their data reset.
I asked if they died at the time and they said all they did was log in and it was reset, that's why it was leading me to believe it occurred after a server restart in some cases.
