### ISSUE TITLE
Mana Batteries loose all their charge constantly (and links break too)

### ISSUE THREAD

**Issue by Bahzur** [Mithion/ArsMagica2#1064] opened 2015-02-10 22:07 UTC
Using Forge 1277 and AM2 1.4.0.008
This seems to happen every time i leave my base, so the chunks the manabatterys are in are unloaded and reloaded. I have a neutral and light prism, and 2 batterys hooked to each of them, no powerconsumers are hooked up. Screenshot from my setup:
![2015-02-10_22 53 58](https://cloud.githubusercontent.com/assets/4956200/6137369/8f63055c-b178-11e4-8d70-395814f975bb.png)
I also just noticed, the same is happening with the altarpiece itself, it had 500 neutral essence in it, that vanished too. This is the battery before i leave:
![2015-02-10_22 55 37](https://cloud.githubusercontent.com/assets/4956200/6137408/e8cc83c0-b178-11e4-95c5-a1be84a41dc4.png)
And after i come back:
![2015-02-10_22 57 43](https://cloud.githubusercontent.com/assets/4956200/6137416/faa72d16-b178-11e4-8c2a-eb591b44d355.png)
Also, all the links between the batterys and obelisks break at the same time as you can notice there, because of nightfall my light prism (moonstonecaps) just started gathering, but the battery got nothing. Before i used no battery, the link between my neutral obelisk and the altar broke too, i noticed that the second time i had to use essence for spellcreation.

This is on a dedicated server, i did not test that in singleplayer.

**Comment by Bahzur** [comment] 2015-02-12 00:23
Just did some further testing, this does not seem to happen in a singleplayer testworld with only Forge and AM2 (and Animationcore). I'll poke around that more, probably creating a testworld on my dedicated server.

**Comment by Mithion** [comment] 2015-02-12 22:00
Does your dedicated server use cauldron or something similar?
Are you using any of the new config options relating to power saving?

**Comment by Bahzur** [comment] 2015-02-12 22:42
No, it doesnt use cauldron. I use only Forge and the most common mods like Thaumcraft, Tinkers' and Chisel2 etc. Modlist:
![ss 2015-02-12 at 11 39 34](https://cloud.githubusercontent.com/assets/4956200/6178572/84fe687e-b310-11e4-80fc-c1e07ba5c2c4.png)
I did some testing with the B:PND_File_WSave config option, but it didnt seem to have an impact. I'll post if i discover more.

**Comment by Bahzur** [comment] 2015-02-13 06:04
I have no friggin' clue why... but... it seems like the manabatteries suddenly started working as they are supposed to do.
I didnt change anything though. There are no new mods nor did i change the config. Nor did i change much in my base, blockwise, because i was busy testing much with the batteries. The last thing i did before was changing the B:PND_File_WSave configoption from true to false, server as also client-wise, and as that didnt do anything, changed that back. But now they suddenly retain their charge (tested several things: restarting the server (which by the way made the battery retain their current value and resetting their values to what they had when the server started again, when that bug happened), switching dimensions, logging out or just going away, all works. Also if the chunks are loaded).

On another note, the rightclick option to show the percentage a battery has is a bit buggy. The value thats printed in chat is always the same, even if they do change their charge. Only when i equip the Magitechgoggles and then rightclick, the percentage printed in chat changes accordingly every rightclick. If i now remove the goggles, the value stays changing right accordingly, BUT if i now test another battery without the goggles, its the same problem. Printing the numeric value with the Magitechs Staff is always correct though. If you want i can open another issue for that bug.

I'll not close this issue yet, because i do not trust this sudden change yet and fear the bug may raise its ugly head again. I'll keep you updated.

And a question: Do light prismen change their total output depending on location? In my singleplayer bugtesting the prism roughly did output the double than my prism on the server does with the same upgrades.

**Comment by Bahzur** [comment] 2015-02-13 09:21
Yup, thats what i feared: They are back to zero percent. I took a break from playing and after i relogged 2 hours later (i did leave Minecraft open), first thing i checked were the batteries, and they are dead again. Important to mention is, rightclicking the batteries still shows the old percentage:
![2015-02-13_10 16 55](https://cloud.githubusercontent.com/assets/4956200/6185039/b609fae2-b369-11e4-9b74-602b505a1479.png)
Next thing ill test is if Fastcraft has anything to do with it, cause it messes with some basic Minecraftstuff afaik.

**Comment by ANTdentarg** [comment] 2015-02-15 10:12
perhaps what batteries are connected with is a factor? I experience something like this as well.

**Comment by Bahzur** [comment] 2015-02-15 10:36
What is your setup? Cause, the last thing i did to test if its the cause was disabling Fastcraft, and right now, it seems to work again. Do you have Fastcraft?

**Comment by ANTdentarg** [comment] 2015-02-15 11:01
negative. if I remember right we share thaumcraft, tinkers, ironchest, nei+waila, and thermal stuff.

**Comment by Bahzur** [comment] 2015-02-15 11:05
Damn. I hoped it was Fastcraft's fault. Same here, ill test more, but for now, the batteries and links did work for a whole day without problems. Really would like to know whats the random cause of this....

**Comment by Mithion** [comment] 2015-02-15 18:09
Heh you and me both. 
I'm sure I'm as tired of this bug cropping up again every time I think I have it fixed as you all are of encountering it. 
I think I know the cause but it's gonna be a bugger to fix for good.

**Comment by Bahzur** [comment] 2015-02-16 06:31
Aaaaand it happened again. Interestingly though this time, only one battery lost its charge. My light prism was able to fill the other battery completly in the 2 days it worked now, and the charge remained.
![2015-02-16_07 25 22](https://cloud.githubusercontent.com/assets/4956200/6207839/559d68a6-b5ad-11e4-9e55-a19712d52ed9.png)
And what do you think is the cause? (im trying to learn Java and how to mod in Minecraft cause i want to update another mod to 1.7, maybe im able to understand what you think it is)

**Comment by Bahzur** [comment] 2015-02-20 08:34
Just a minor update, still happening randomly. I noticed another thing; while the battery connected to the light prism had nothing anymore, the light prism itself had just a small bit (about 7 etherium). Seems like that time, when i disconnected the day before, it was night ingame and the prism was charging, but when i reconnected again the next day, it was day ingame and the prism stopped (mooncaps) and at the same time the battery lost its charge (?), with the prism just having a remnant that didnt yet get transferred. The link broke too, again.

**Comment by Mithion** [comment] 2015-02-22 17:03
Can you also post your current AM2 config please?

**Comment by Bahzur** [comment] 2015-02-22 17:10
Here: http://pastebin.com/zdRhwEkH

**Comment by Mithion** [comment] 2015-02-22 17:10
Thanks!

**Comment by Bahzur** [comment] 2015-02-22 17:10
No problem.

**Comment by Bahzur** [comment] 2015-03-02 02:53
Update: So, for a week (!) nothing happened with the batteries, they were happily holding on to their charge. Unfortunately yesterday they fellt like they didnt want to anymore, as also today. I still have absolutly no clue why/how/when that happens (except that it only happens when the chunk is unloaded/reloaded). *sigh*

**Comment by Bahzur** [comment] 2015-03-03 00:33
Everytime i restart the server (about every 2-3 days) i use /save-all before shutdown, this seems to help a bit, not sure though.

**Comment by Bahzur** [comment] 2015-04-10 17:09
Another Update: So, for weeks now it didnt happen. In the meantime i updated several mods and added a few, it may be that something now prevents that loss or something was causing this. Inbefore me reporting back tomorrow with a loss of all etherium... ^^

**Comment by 252rer** [comment] 2015-06-05 23:49
Last time i was having any problems with this I had setup my nexus in a mystcraft world with chickenchunks loader loading it and had no space between most of the battery and machines connections. This time in the overworld with at least 1 block of space for the I assume invis connections between blocks, same chunkloader on a new server I'm not having any issues other then clicking on the battery without a magictech staff always saying 0% charged even at full charge. I have not lost power all the time like I used to though.

**Comment by Mithion** [comment] 2015-06-05 23:51
There aren't any invisible blocks for the power system, so you don't need any space between them in order to have them work properly.  anywhere within 10 blocks will work the same.

As for the issue, still working on it.  Making progress though!

**Comment by 252rer** [comment] 2015-06-05 23:56
Ah I had gotten a little superstitious it seems.

**Comment by Mithion** [comment] 2015-06-25 02:12
I believe I have this fixed in 1.4.0.009 Dev.
However without a reliable way to replicate it, I can't be 100% sure.
I'm going to close this issue as all testing has been successful.  Please comment again or open a new issue referencing this one if the issue persists in 1.4.0.009 once released.

**Closed by Mithion** 2015-06-25 02:12 UTC
Labels: Partially Fixed

**Comment by Bahzur** [comment] 2015-06-25 07:57
Will do that.

**Comment by HunterRS** [comment] 2017-05-01 14:56
Issue again in 1.4.0.009

**Comment by Jason200101** [comment] 2017-07-28 23:58
The bug isn't consistant. I just made a super long chain between point A and B with distance almost 1000 blocks. I did that using etherium conduits and placing 10 between each mana battery to keep it conected, since etherium conduits only reach a distance of 100 blocks.

At the start of the chain, everything is fine. Batteries don't lose connection and keep everything at sync, even when I reload the chunks they're intact. When the chain reaches the point where my base is reloaded, those two mana batteries lose connection and etherium stores inside. That also happens with my light prism and obelisk, as well as all mana batteries I have over there, but the altar doesn't lose power nor connections are broken for it. This doesn't seem to affect the mana batteries at the start of the chain however.

I'm using Botania, Thaumcraft (with addons), Blood Magic, vein miner and damage indicators.
(and ars magica 2, of course)

I can also verify that this is a server side bug. I just tested it on single player, and then opened Lan. The bug only happened while I was on Lan.

**Comment by DrJigglebones** [comment] 2017-10-25 11:00
Weighing in that I'm also still having this issue in 1.4.0.009. I have my black aurem deep underground by a zombie spawner. That one regularly disconnects and drains its battery. My celestial prism and obelisk are both near my base, and they unlink and drain charge much less often. Running the LoTRCircles modpack via Technic Launcher. If I had to guess, it probably happens due to the mana batteries loading in at a significantly different time than the power sources, but I've done no testing to back up that claim. That's just from personal anecdotes.

**Comment by Th3l0stSpart4n** [comment] 2017-10-25 15:37
I have also noticed this and fixed it by chunkloading my whole setup using ftb utilities.

**Comment by DrJigglebones** [comment] 2017-10-25 22:43
I've done the same thing using chickenchunks like 252rer and it's working, but it's still not an ideal fix. Then again it seems AM2 has had support pretty much dropped for 2 years now :(

UPDATE: It's happened again even with the chunk loader... :/ I've set up 4 more now, so each part has its own chunk loader rather than one single loader covering everything

UPDATE 2: The charge is back from nowhere, guessing it was just a graphical glitch earlier. in any case, seems to be working fine atm

**Comment by TheIcyOne** [comment] 2017-10-27 14:48
1.7.10 has had support dropped for like 2 years ;) The 1.10+ versions were dropped about 3 months ago.

**Comment by Th3l0stSpart4n** [comment] 2017-10-27 15:23
Are they actually abandoning 1.10 and moving to 1.12 or dropping it all together, or just a lull?
