### ISSUE TITLE
Projectile+AOE dig not using dig modifiers untill 'cast mode' is pressed

### ISSUE THREAD

**Issue by Rodg88** [Mithion/ArsMagica2#934] opened 2014-10-09 07:15 UTC
I made a spell with a single shape of Projectile + AOE, with Dig + feather touch, but it doesn't apply the silk touch effect until I press the C key, after which the spell works as expected. Pressing C again doesn't change anything. If I make it without AOE, the silk touch effect works straight away. Also happens with Prosperity instead of feather touch. Untested with effects other than dig...

**Comment by EoD** [comment] 2015-01-05 09:31
It is not limited to projectile: it's the same issue with "Touch+AoE" and probably "AoE" alone.

**Comment by Mithion** [comment] 2015-01-20 01:35
Duplicate of #891

**Closed by Mithion** 2015-01-20 01:35 UTC
Labels: bug, Low Priority
