### ISSUE TITLE
[AM2 1.4.0.008] [MC 1.7.10] Calefactor Crashes Clients on Use.

### ISSUE THREAD

**Issue by AutoJukebox** [Mithion/ArsMagica2#1207] opened 2015-07-22 14:55 UTC
So i added Ars Magica 2 to my modpack and whenever a player interacts with the Calefactor when the calefactor has items in it (i.e iron ) their client gets kicked off the server with lost connection: Internal Exception: java.io.IOException: Connection reset by peer and crashes client side..... Is there anyway to fix this?

Thanks. 
Crash Report: http://pastebin.com/tqyAs3Wr
My modlist: http://pastebin.com/BjFcJdjU
FML-client-latest: http://pastebin.com/93ktjsez

**Comment by AutoJukebox** [comment] 2015-07-24 22:18
Is this mod still have support? :/

**Comment by TherminatorX** [comment] 2015-07-24 23:36
@AutoJukebox Always wait a week for developer response. Are you using Bukkit?

**Comment by AutoJukebox** [comment] 2015-07-25 02:20
@TherminatorX Yes, I am using cauldron

**Comment by TherminatorX** [comment] 2015-07-26 02:05
See if you can reproduce it without Cauldron or Bukkit. AM2 doesn't support them.

**Comment by LemADEC** [comment] 2015-08-27 09:03
Is this still reproduced?

**Comment by TherminatorX** [comment] 2015-08-29 04:39
@LemADEC Since there was no response, unsure. Can you reproduce it?

**Comment by LemADEC** [comment] 2015-08-29 14:01
I wasn't able to reproduce in SMP with Cauldron-1.7.10-1481.148 + am2-1.4.0.008.
I was using my beta modpack 8.0.1 http://www.technicpack.net/modpack/tdks-world-war-minecraft-beta.260585 .
I've tried also in SSP with VoltzEngine + ICBM in vain.

**Comment by jjtParadox** [comment] 2015-09-18 04:19
This has been fixed by #1248.

**Closed** 2015-09-18 12:07 UTC
