### ISSUE TITLE
Crash when picking up Wakebloom in version 1.4.0.007

### ISSUE THREAD

**Issue by Masti6** [Mithion/ArsMagica2#1037] opened 2015-02-07 00:39 UTC
FML Client log from the session where I only opened the client, connected to server, threw a Wakebloom on the floor and tried to pick it up, after which I was kicked from the server and closed the game.
https://dl.dropboxusercontent.com/u/47056596/fml-client-latest.log

I just finished updating the mod from 1.4.0.006 to 1.4.0.007 and while it gave me an error while using the new API zip you linked on the thread, I tried to leave the old Animation API .jar file in the mods folder as well, and it worked with that.
Except now, when I tried to pick up a Wakebloom, my game boots me out of my server immediately. I haven't tried if this is the case with other AM2 herbs as well or if it's only AM2 items that causes this but I'll be testing that shortly.

What I can say for sure is that this didn't happen in the 006 version.

**Comment by Masti6** [comment] 2015-02-07 00:45
Confirmed, other items cause this as well. According to the thread, it may indeed be something related to the compendium and unlocking new items and/or achievements there.
The client gives an Internal server error when picking up an item that would produce a compendium entry even with the staged compendium option turned off. (Show everything from the start).

**Comment by Mithion** [comment] 2015-02-07 00:45
I'm currently uploading a build that should resolve this issue.

**Comment by Masti6** [comment] 2015-02-07 00:47
Brilliant! Could you reply in this issue when it's up with the usual "Fixed in build #"?
A question about the new API link while you're here, I downloaded the zip file and deleted the old animation api .jar file and the game wouldn't recognize the new API zipfile as proper animation API.
Is this intended, as in I need to have the old API with the new ZIP in order for it to work or should the new Animation API zipfile work alone with the core AM2?

**Comment by Mithion** [comment] 2015-02-07 00:49
Link is up: https://www.dropbox.com/s/6vihegwd561r2ab/1.7.10_AM2-1.4.0.008.jar?dl=1
Please download and confirm if the issue is resolved.

You misunderstand; the API I have linked is for other developers to make their mods interact with AM2 (add new powered blocks, spell parts, items, etc.)
For AnimAPI you will still need to download it from TheHippoMaster21's OP.

**Comment by Masti6** [comment] 2015-02-07 00:50
Ah, roger that.
It was kind of bundled with the mod download link so I thought it was an update to the API used with the mod.
Applying the updated mod now for testing.

**Comment by Masti6** [comment] 2015-02-07 00:55
Confirmed. Picking these items up no longer causes an internal server error.
Thanks for the swift fix.

**Comment by Mithion** [comment] 2015-02-07 00:56
No problem!
Closing as resolved in 1.4.0.008.

**Closed by Mithion** 2015-02-07 00:56 UTC
