### ISSUE TITLE
very strange issue with HEE

### ISSUE THREAD

**Issue by banjomarx** [Mithion/ArsMagica2#1139] opened 2015-04-11 19:35 UTC
I had a series of odd crashes with Hardcore Ender Expansion trying to attribute mana to one of the mobs?! can you take a look? this is a link to the issue i posted there so hopefully there can be collaboration
https://github.com/chylex/Hardcore-Ender-Expansion/issues/109

**Comment by banjomarx** [comment] 2015-04-11 20:16
http://pastebin.com/sHGWXzzu
ok he says its not in his code (idk whats going on there) 
this is the crash http://pastebin.com/sHGWXzzu

**Comment by TherminatorX** [comment] 2015-04-11 23:49
Get Cauldron out of the situation, as Chy suggested, and post a new (accepted) crashlog

**Comment by banjomarx** [comment] 2015-04-11 23:53
um but cauldron is kinda necessary for my server, we depend heavily on plugins. is there an alternative? i didnt think sponge was working yet

**Comment by TherminatorX** [comment] 2015-04-12 00:46
Well, does it happen in singleplayer?

**Comment by banjomarx** [comment] 2015-04-12 00:54
im not quite sure how to reproduce, any ideas? one of my players must have somehow triggered it but i dont know exactly how, i asked around. its not a common problem but it hit a bunch of times in a row for no apparent reason (people were just exploring the end)

**Comment by banjomarx** [comment] 2015-04-12 00:54
since then it hasnt happened though thankfully

**Comment by TherminatorX** [comment] 2015-04-12 00:56
Well, it's calling it at "chylex.hee.entity.boss.EntityMiniBossEnderEye," so I'd check there.

**Comment by chylex** [comment] 2015-04-12 10:47
Someone replicated the issue without cauldron: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1281889-hardcore-ender-expansion-v1-8-200-000-dls?comment=2064

**Comment by Xanarios** [comment] 2015-04-25 12:26
If it helps, I have recreated this error using strictly AM2 1.4.0.008 / HEE 1.8.1 / NEI (and library dependencies) under Forge 10.13.3.1389.  Seems to be related to the onLivingUpdates on the Ender Eye entity (chylex.hee.entity.boss.EntityMiniBossEnderEye).  Traces to a NPE somewhere in AM2's extended properties (am2.playerextensions.ExtendedProperties.getMaxMana).

Steps to reproduce from a fresh install are as follows:

1) Create new world
2) Create minimal end portal
3) Fly around for a little while until crash.

Crash Report: http://pastebin.com/WAzxV5qQ 
Full Error Log: https://www.mediafire.com/?012k6rtodffne9f

Cross Referencing Back to https://github.com/chylex/Hardcore-Ender-Expansion/issues/109

**Comment by chylex** [comment] 2015-05-09 08:48
The extended properties of AM2 cannot handle the world being null at the time of entity creation. The properties get ignored and then crash the game later when AM2 automatically assumes every single entity has them.

**Comment by Xyphius** [comment] 2015-05-20 21:57
Since this is the same issue as https://github.com/Mithion/ArsMagica2/issues/1157 (yes, newer post than this one... sorry), I have added a null check for this purpose. Resolved in 1.4.0.009 DEV

**Closed by Xyphius** 2015-05-20 21:57 UTC
