### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by CrowAU** [Mithion/ArsMagica2#1049] opened 2015-02-08 16:47 UTC
After imbue nano legs from IC2 with dispelling I get "Internet Server Error" and I am now unable to join the server once again, this only happened after I attempted to put the leg piece back on after taking it out of the imbue table, I've attempted to kill myself and also rollback ars magica to an earlier version to remove the ability thinking it would do something but to no avail.

**Comment by Mithion** [comment] 2015-02-08 16:59
Duplicate of #1039

**Closed by Mithion** 2015-02-08 16:59 UTC
Labels: duplicate
