### ISSUE TITLE
Unable to break Mage Lights

### ISSUE THREAD

**Issue by Roxforbraynz** [Mithion/ArsMagica2#1005] opened 2015-01-19 11:30 UTC
When I try to break a Mage Light (created by the Light component) to clear an area to expand my farm, whenever I try to place something where it was, it pops right back into existence. This will cause severe problems for me as I lit up all around my base with Mage Lights. I can't find any information about a special way to break them, so I'm assuming this is a bug.

This is in the latest version as of this post. (1.4.0.006)

**Comment by Slychocobo** [comment] 2015-01-19 20:11
Suffering from the same issue here.

Just placing a light down and trying to break/smash them removes the light, but placing another block on top of it causes it to spawn back in instead.

**Comment by Mithion** [comment] 2015-01-19 20:14
This is a duplicate of ... some number I can't remember off the top of my head.
Bottom line, though, is that I am aware of this issue and have fixed it in the dev copy, version 1.4.0.007.  It will be ready to release soon.

Thanks for letting me know though!

**Closed by Mithion** 2015-01-19 20:14 UTC
Labels: duplicate

**Comment by ShadoDragon** [comment] 2015-01-19 20:17
You can use a dig spell to permanently break the light

**Comment by Mithion** [comment] 2015-01-19 20:20
Right, I had forgotten that workaround - good solution for the time being.
