### ISSUE TITLE
Looks like buildcraft and AM2 issue again

### ISSUE THREAD

**Issue by crunkazcanbe** [Mithion/ArsMagica2#1080] opened 2015-02-19 01:06 UTC
As the title says ,but I am not for sure . All I know is my log was getting filled up with http://pastebin.com/PBkLXZEE ..

What I think it is is buildcraft is trying to add some blocks from AM2 as Facades and its failing .
If that is the case could you tell me the exact names I would put in the black list of blocks to not be Facades in the buildcraft config ?

Thank you!

-Crunk

EDIT:Also just now as I was scrolling through the creative Tab for AM2 I notice all of this http://pastebin.com/2JDFbRNr pop up on the console . Just though I would let you know.

**Comment by Mithion** [comment] 2015-02-19 19:32
I'm thinking this is going to have to be fixed on BC's side.  I can't tell where the problem is from the paste you supplied.  If they can point out a method I need to override or a specific return value they need, I can look into it.

As for the edit...you using NEI?  It might be something related to the fact that the trunk from OpenBlocks isn't actually in the world and is instead in the NEI gui.

**Closed** 2015-06-25 00:30 UTC
Labels: Inter-Mod Compat Issue
