### ISSUE TITLE
java.lang.IllegalArgumentException: resource AM2_at.cfg not found.

### ISSUE THREAD

**Issue by chezpaul** [Mithion/ArsMagica2#1429] opened 2016-02-17 17:25 UTC
I've been getting this on my server since 008.

[09:18:55 ERROR]: A critical problem occurred registering the ASM transformer class am2.preloader.AccessTransformers
java.lang.IllegalArgumentException: resource AM2_at.cfg not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148) ~[server-1.7.10.jar:?]
	at com.google.common.io.Resources.getResource(Resources.java:229) ~[server-1.7.10.jar:?]
	at cpw.mods.fml.common.asm.transformers.AccessTransformer.readMapFile(AccessTransformer.java:118) ~[KCauldron-1.7.10-1614.188.jar:1.7.10-1614.188]
	at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:101) ~[KCauldron-1.7.10-1614.188.jar:1.7.10-1614.188]
	at am2.preloader.AccessTransformers.<init>(AccessTransformers.java:10) ~[AccessTransformers.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_60]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_60]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:109) [KCauldron-1.7.10-1614.188.jar:1.7.10-1614.188]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [KCauldron-1.7.10-1614.188.jar:1.7.10-1614.188]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [KCauldron-1.7.10-1614.188.jar:1.7.10-1614.188]
[09:18:55 INFO]: Core: Located Thaumcraft in Thaumcraft-1.7.10-4.2.3.5.jar

**Comment by Mithion** [comment] 2016-02-17 17:35
This is a duplicate bug report - we're aware of the issue and it's caused by defining an access transformer as a requirement (incorrectly), but not including it in the jar (correctly, as we don't need one!).

This is only console spam and won't have a negative effect on your ability to play the mod (no crashes or problems of any sort).  It will be fixed for sure in the 1.8 update, but I can't say for sure regarding 1.7.10.

**Closed by Mithion** 2016-02-17 17:35 UTC

**Comment by chezpaul** [comment] 2016-02-17 17:57
k cool
Thanks
