### ISSUE TITLE
Can't get harvest plants to work

### ISSUE THREAD

**Issue by mrcgamer** [Mithion/ArsMagica2#1164] opened 2015-05-21 03:53 UTC
I can't seem to get the harvest plants component to work correctly. The only plant it will harvest is flowers from the botania mod, it won't harvest grass or wheat, and it only works if I target a block above the flowers. I have tried various combinations of just projectile, AoE, harvest and target non-solid blocks and even beam, but it does not work unless the projectile hits a block. It does work if I use zone and area of effect.

I was trying to get the spell to farm for tarma root, Zone | Duration | Duration | Duration | AoE | Grow plants | Harvest plants, but grow does not seem to work with zone. It works if I add projectile at the start, but then harvest does not work. It does show the brown particles that I assume are a part of the harvest component, but it won't harvest anything, not even the botania flowers. I have also noticed that this isn't growing any tarma root, even when I place grass blocks underground and have it at 0 light level.

Not sure if this is a bug or if things changed, but I can't seem to find anything recent on this. Thanks.

**Comment by Bahzur** [comment] 2015-06-02 22:27
Its on the second page on open bugs, here: #1083

**Comment by Mithion** [comment] 2015-06-04 02:23
Duplicate of #1083, closing.

**Closed by Mithion** 2015-06-04 02:23 UTC
