### ISSUE TITLE
Server crash - A fatal error has been detected by the Java Runtime Environment:

### ISSUE THREAD

**Issue by ProsperCraft** [Mithion/ArsMagica2#1135] opened 2015-04-03 00:23 UTC
http://pastebin.com/FQtpFzzX

Not repeatable.

I was crafting a project spell of lightning damage.

**Comment by Mithion** [comment] 2015-04-09 00:53
JRE crashes aren't something caused by me - closing as not an AM2 issue.

**Closed by Mithion** 2015-04-09 00:53 UTC
