### ISSUE TITLE
When I leave the End AM2 data gets reset

### ISSUE THREAD

**Issue by TheMonkey78** [Mithion/ArsMagica2#1156] opened 2015-05-04 19:54 UTC
So whenever I leave the end, my XP level gets reset to 6 and my AM2 level sometimes gets reset. I have to go get the basic offence spell and a few others for it to be fixed. I am using Forge 1.7.10 1291 and the latest version of AM2 as of me posting this. The only spell I have disabled is Shrink due to Morph mod glitches. I have also been having a glitch where every time I restart the server I need to turn KeepInventory back to false, yet this doesn't happen with other gamerules, but I don't think AM2 is the cause of this. I am using this modpack I created myself, here are the windows and mac versions. The bug occurs on both. http://www.technicpack.net/modpack/all-around-awesomeness-aaa-2.616088 http://www.technicpack.net/modpack/all-around-awesomeness-2-mac.616128

**Comment by jjtParadox** [comment] 2015-09-20 18:34
I believe this should have been fixed by #1231, or by #1246, but I can try using your modpack and the updated version of AM2 to test if it has been fixed.

**Comment by jjtParadox** [comment] 2015-09-20 19:01
Just tested getting a few levels, going to the end, leveling up some more, then going back to the overworld. So far no levels have been lost. As for the gamerule reset, there's nothing in the AM2 code that sets any game rules.

**Comment by Mithion** [comment] 2015-09-21 01:06
AM2 doesn't mess with any game rules, I can confirm this.
Since this is testing well, I'm going to close this as resolved in dev.  If after the update you find that it still happens under certain circumstances we can re-open the issue.

**Closed by Mithion** 2015-09-21 01:06 UTC
