### ISSUE TITLE
Failed to load extended properties for ArsMagicaExProps.  This is a mod issue. (according to forge logs)

### ISSUE THREAD

**Issue by renadi** [Mithion/ArsMagica2#1195] opened 2015-07-02 19:09 UTC
Forge says it failed to load extended properties, I don't see any negative effects from it, but figured it should be mentioned.

http://pastebin.com/uf3dcep9

**Comment by jjtParadox** [comment] 2015-09-21 17:05
Does something specific cause this error? What version of AM2 and other mods are you using?

**Comment by jjtParadox** [comment] 2015-09-26 22:44
After some digging, I found this error to be caused by the minecraft `EntityList.createEntityFromNBT()` method, as that method creates an entity without giving the entity a world.

In the current AM2 `ExtendedProperties`, an entity must have a world before the extended properties will accept and save the entity in a field. However, the extended properties for an entity created with `createEntityFromNBT()` can still be refrenced, causing NPEs whenever methods in `ExtendedProperties` are called on the world-less entity.

This could probably be fixed with accepting an entity if it doesn't have a world and adding lots of `entity.worldObj != null` checks to `ExtendedProperties`, or possibly a boolean field if the entity's world is valid.

@Mithion, thoughts?

**Comment by jjtParadox** [comment] 2015-09-27 03:13
Actually, this may be a bug with Thaumic Horizons instead, as it passes a null value into `EntityList.createEntityFromNBT()`. I misinterpreted that method, as it has an argument for the world, but Thaumic Horizons doesn't pass a world to that method.

Should AM2 still try to avoid errors if a null value is passed for a world?

**Comment by Mithion** [comment] 2015-09-27 14:07
AM2 already does it's best to avoid errors in this case - for example, it will try to load the extended properties. If that fails due to scenarios like this, the error message will be logged by the implementation in the Forge base classes, and will return null.  AM2 checks for this and instead uses a dummy extended properties so as not to crash.

The error messages are important so that errors like these can be found and fixed.  In this case, it isn't an AM2 bug, that's just where it surfaces.  We're actually handling it quite gracefully at this point already.

**Comment by jjtParadox** [comment] 2015-09-27 17:07
Good to know :)

We can probably close this then and refer this to Thaumic Horizons.

**Comment by Mithion** [comment] 2015-09-28 16:14
Closing as not an AM2 issue.

**Closed by Mithion** 2015-09-28 16:14 UTC
